# Generated by Django 4.0 on 2026-07-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
