# Generated by Django 4.0 on 2026-07-03 13:24

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0004_awards_unique_name_ci'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='awards',
            name='unique_award_owner_name_ci',
        ),
        migrations.AddConstraint(
            model_name='awards',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.expressions.F('owner'), name='unique_award_owner_name'),
        ),
    ]
