# Generated by Django 4.0 on 2026-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0005_remove_awards_unique_award_owner_name_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblefilm',
            name='cache_LOD',
            field=models.IntegerField(default=0, help_text='Cache Level of Detail: 0 = no cache, 1 = title only, 2 = basic info'),
        ),
        migrations.AddField(
            model_name='eligiblefilm',
            name='cached_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eligiblefilm',
            name='cached_poster_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eligiblefilm',
            name='cached_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligiblefilm',
            name='cached_tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
