# Generated by Django 4.0 on 2026-07-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fauxcademy', '0008_awards_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEligibleFilmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('eligible_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='fauxcademy.eligiblefilm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_statuses', to='auth.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usereligiblefilmstatus',
            constraint=models.UniqueConstraint(fields=('user', 'eligible_film'), name='unique_user_eligible_film_status'),
        ),
    ]
