# Generated by Django 4.0 on 2026-07-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0012_awardcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardcategory',
            options={'ordering': ['importance', 'name']},
        ),
    ]
