# Generated by Django 4.0 on 2026-07-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0013_alter_awardcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('cache_LOD', models.IntegerField(default=0, help_text='Cache Level of Detail: 0 = no cache, 1 = title only, 2 = basic info')),
                ('cached_name', models.CharField(blank=True, max_length=200)),
                ('cached_biography', models.CharField(blank=True, max_length=200)),
                ('cached_poster_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='nominated_person_tmdb_id',
        ),
        migrations.AddField(
            model_name='nomination',
            name='nominated_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fauxcademy.nominatedperson'),
        ),
    ]
