# Generated by Django 4.0 on 2026-07-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0014_nominatedperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='nominated_role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
