# Generated by Django 4.0 on 2026-07-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0015_nomination_nominated_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nominated_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
