# Generated by Django 4.0 on 2026-07-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0016_alter_nomination_nominated_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
