# Generated by Django 4.0 on 2026-07-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauxcademy', '0017_alter_nomination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligiblefilm',
            name='cached_poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nominatedperson',
            name='cached_poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
