# Generated by Django 4.0 on 2026-07-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fauxcademy', '0018_alter_eligiblefilm_cached_poster_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fauxcademy.awardcategory')),
                ('first_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choice_ballots', to='fauxcademy.nomination')),
                ('second_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choice_ballots', to='fauxcademy.nomination')),
                ('third_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_choice_ballots', to='fauxcademy.nomination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_user_category_ballot'),
        ),
    ]
