# Generated by Django 4.0.6 on 2023-09-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joewebapp', '0002_alter_sketch_options_sketch_templatename_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sketch',
        ),
    ]
