name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          cd /var/www/Joe-Web
          git fetch origin
          git reset --hard origin/main