# Generated by Django 4.0 on 2026-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photooftheday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosubmission',
            options={'ordering': ('-date', 'user')},
        ),
        migrations.RemoveField(
            model_name='photosubmission',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='photosubmission',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
