# Generated by Django 4.0 on 2026-09-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photooftheday', '0002_alter_photosubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosubmission',
            name='cached_address',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
