# Generated by Django 4.0.6 on 2022-07-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugrank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mug',
            old_name='list_id',
            new_name='list',
        ),
        migrations.AlterField(
            model_name='mug',
            name='elo',
            field=models.FloatField(default=1000),
        ),
    ]
