# Generated by Django 4.0.6 on 2022-07-23 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mugrank', '0003_list_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List_User',
            new_name='ListUser',
        ),
    ]
