# Generated by Django 4.0.6 on 2022-07-23 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mugrank', '0004_rename_list_user_listuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mug',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MugRankRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_won', models.BooleanField()),
                ('mug_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mug_one', to='mugrank.mug')),
                ('mug_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mug_two', to='mugrank.mug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
