# Generated by Django 4.0.6 on 2022-07-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugrank', '0005_alter_mug_name_mugrankrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mug',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
