# Generated by Django 4.0.6 on 2022-07-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugrank', '0007_alter_mug_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='listuser',
            name='completed_rankings',
            field=models.BooleanField(default=False),
        ),
    ]
