# Generated by Django 4.0.6 on 2022-07-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugrank', '0008_listuser_completed_rankings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listuser',
            name='completed_rankings',
        ),
        migrations.AddField(
            model_name='listuser',
            name='unique_matchups_rated',
            field=models.IntegerField(default=0),
        ),
    ]
