# Generated by Django 4.0.6 on 2023-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugrank', '0010_remove_listuser_unique_matchups_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='showStats',
            field=models.BooleanField(default=True),
        ),
    ]
