# Generated by Django 4.0 on 2024-02-27 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mugrank', '0011_list_showstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmMug',
            fields=[
                ('mug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mugrank.mug')),
                ('tmdb_id', models.IntegerField()),
                ('letterboxd_slug', models.CharField(blank=True, max_length=100)),
            ],
            bases=('mugrank.mug',),
        ),
    ]
