# Generated by Django 4.0 on 2024-07-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mugrank', '0013_list_filmlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmList',
            fields=[
                ('list_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mugrank.list')),
                ('letterboxdLID', models.CharField(default='', max_length=100)),
            ],
            bases=('mugrank.list',),
        ),
    ]
