# Generated by Django 4.0 on 2024-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugrank', '0014_filmlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmmug',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='filmmug',
            name='poster_format_str',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
