# Generated by Django 4.0.6 on 2023-10-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusdisplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
