# Generated by Django 4.0 on 2024-02-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusdisplay', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='lineFour',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='lineOne',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='lineThree',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='lineTwo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
